apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-5g
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain # Retain or Delete
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data" # Delete can only work under /tmp
