apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
    }

    server {
      listen 443 ssl;
      ssl_certificate /etc/ssl/certs/localhost.crt;
      ssl_certificate_key /etc/ssl/certs/localhost.key;
      root /usr/share/nginx/html;
    }
