apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  labels:
    k8s-app: mariadb
type: Opaque
data:
  mysql_database: bWFyaWFkYg== # mariadb
  mysql_user: bWFyaWFkYg==     # mariadb
  mysql_password: bWFyaWFkYl9wYXNz # mariadb_pass
  mysql_root_password: bWFyaWFkYl9yb290X3Bhc3M= # mariadb_root_pass

